apiVersion: v1
kind: Service
metadata:
  name: lab-02-service
  labels:
    app: k8s-python-web
    owner: GlebBurov
spec:
  selector:
    project: lab-02
  ports:
    - name: python-app
      protocol: TCP
      port: 5000
      targetPort: 5000
  type: NodePort